kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "kodadok.fullname" . }}
  labels:
    {{- include "kodadok.labels" . | nindent 4 }}
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: {{ .Values.workspace.storage }}