{{- if .Values.editor.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kodadok.serviceAccountName" . }}
  labels:
    {{- include "kodadok.labels" . | nindent 4 }}
  {{- with .Values.editor.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
