# Default values for kodadok.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

workspace:
  username: kodadoker
  # password: my-sample-password
  storage: "10Gi"
  ingress:
    enabled: false
    annotations: {}
      # kubernetes.io/ingress.class: nginx
      # kubernetes.io/tls-acme: "true"
    hosts:
      - host: chart-example.local
        paths:
          - path: /
            port: 3000
            name: frontend
          - path: /
            port: 8080
            name: backend
    tls: []
    #  - secretName: chart-example-tls
    #    hosts:
    #      - chart-example.local

editor:
  image:
    repository: kodadok/code-server-node-jdk
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: latest
  imagePullSecrets: []
  securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000
  resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi
  service:
    type: ClusterIP
    port: 28801
  ingress:
    enabled: false
    annotations: {}
      # kubernetes.io/ingress.class: nginx
      # kubernetes.io/tls-acme: "true"
    hosts:
      - host: chart-example.local
        paths: []
    tls: []
    #  - secretName: chart-example-tls
    #    hosts:
    #      - chart-example.local
  serviceAccount:
    # Specifies whether a service account should be created
    create: false
    # Annotations to add to the service account
    annotations: {}
    # The name of the service account to use.
    # If not set and create is true, a name is generated using the fullname template
    name: ""

docker: 
  enabled: true
  image:
    repository: docker
    pullPolicy: IfNotPresent
    tag: 19.03.13-dind
  resources:
    requests:
      memory: "512Mi"
      cpu: "500m"
    limits:
      memory: "3Gi"
      cpu: "2000m"

nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

nodeSelector: {}

tolerations: []

affinity: {}

revisionHistoryLimit: 1