name: Workspaces
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '5 4 * * 6'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: dorny/paths-filter@v2.2.1
      if: ${{ github.event_name != 'schedule' && github.event_name != 'workflow_dispatch' }}
      id: filter
      with:
        filters: |
          codeserver:
            - 'workspaces/kodadok-code-server/**/*'
          codeserver_node:
            - 'workspaces/kodadok-code-server/**/*'
            - 'workspaces/kodadok-modules/docker'
            - 'workspaces/kodadok-modules/node'
          codeserver_jdk8:
            - 'workspaces/kodadok-code-server/**/*'
            - 'workspaces/kodadok-modules/docker'
            - 'workspaces/kodadok-modules/node'
            - 'workspaces/kodadok-modules/jdk8'
          codeserver_jdk14:
            - 'workspaces/kodadok-code-server/**/*'
            - 'workspaces/kodadok-modules/docker'
            - 'workspaces/kodadok-modules/node'
            - 'workspaces/kodadok-modules/jdk14'
          codeserver_golang:
            - 'workspaces/kodadok-code-server/**/*'
            - 'workspaces/kodadok-modules/docker'
            - 'workspaces/kodadok-modules/node'
            - 'workspaces/kodadok-modules/golang'
          theia:
            - 'workspaces/kodadok-theia/**/*'
          theia_node:
            - 'workspaces/kodadok-theia/**/*'
            - 'workspaces/kodadok-modules/docker'
            - 'workspaces/kodadok-modules/node'
          theia_jdk:
            - 'workspaces/kodadok-theia/**/*'
            - 'workspaces/kodadok-modules/docker'
            - 'workspaces/kodadok-modules/node'
            - 'workspaces/kodadok-modules/jdk8'
            - 'workspaces/kodadok-modules/jdk14'
          theia_golang:
            - 'workspaces/kodadok-theia/**/*'
            - 'workspaces/kodadok-modules/docker'
            - 'workspaces/kodadok-modules/node'
            - 'workspaces/kodadok-modules/golang'
    - name: docker login
      uses: docker/login-action@v1.3.0
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    - name: build kodadok/code-server
      if: ${{ steps.filter.outputs.codeserver == 'true' || github.event_name == 'schedule' || github.event_name == 'workflow_dispatch' }}
      run: ./bin/kodadok-build -e code-server
    - name: build kodadok/code-server-node
      if: ${{ steps.filter.outputs.codeserver_node == 'true' || github.event_name == 'schedule' || github.event_name == 'workflow_dispatch' }}
      run: ./bin/kodadok-build -t kodadok/code-server-node -e code-server -p node,docker
    - name: build kodadok/code-server-node-jdk8
      if: ${{ steps.filter.outputs.codeserver_jdk8 == 'true' || github.event_name == 'schedule' || github.event_name == 'workflow_dispatch' }}
      run: ./bin/kodadok-build -t kodadok/code-server-node-jdk8 -e code-server -p node,docker,jdk8
    - name: build kodadok/code-server-node-jdk14
      if: ${{ steps.filter.outputs.codeserver_jdk14 == 'true' || github.event_name == 'schedule' || github.event_name == 'workflow_dispatch' }}
      run: ./bin/kodadok-build -t kodadok/code-server-node-jdk14 -e code-server -p node,docker,jdk14
    - name: build kodadok/code-server-node-golang
      if: ${{ steps.filter.outputs.codeserver_golang == 'true' || github.event_name == 'schedule' || github.event_name == 'workflow_dispatch' }}
      run: ./bin/kodadok-build -t kodadok/code-server-node-golang -e code-server -p node,docker,golang
    - name: build kodadok/theia
      if: ${{ steps.filter.outputs.theia == 'true' || github.event_name == 'schedule' || github.event_name == 'workflow_dispatch' }}
      run: ./bin/kodadok-build -e theia
    - name: build kodadok/theia-node
      if: ${{ steps.filter.outputs.theia_node == 'true' || github.event_name == 'schedule' || github.event_name == 'workflow_dispatch' }}
      run: ./bin/kodadok-build -t kodadok/theia-node -e theia -p node,docker
    - name: build kodadok/theia-node-jdk8
      if: ${{ steps.filter.outputs.theia_jdk8 == 'true' || github.event_name == 'schedule' || github.event_name == 'workflow_dispatch' }}
      run: ./bin/kodadok-build -t kodadok/theia-node-jdk8 -e theia -p node,docker,jdk8
    - name: build kodadok/theia-node-jdk14
      if: ${{ steps.filter.outputs.theia_jdk14 == 'true' || github.event_name == 'schedule' || github.event_name == 'workflow_dispatch' }}
      run: ./bin/kodadok-build -t kodadok/theia-node-jdk14 -e theia -p node,docker,jdk14
    - name: build kodadok/theia-node-golang
      if: ${{ steps.filter.outputs.theia_golang == 'true' || github.event_name == 'schedule' || github.event_name == 'workflow_dispatch' }}
      run: ./bin/kodadok-build -t kodadok/theia-node-golang -e theia -p node,docker,golang
